### ISSUE TITLE
Edit and Remove links don't show up in Umbraco 7.4.0-RC1

### ISSUE THREAD

**Issue by greystate** [rolfis/ExtendedMediaPicker#9]
I've installed **Extended MediaPicker** in v7.4.0-RC1 and there seems to be some style-clashes that affects the links to **Edit** and **Remove**.

Umbraco's CSS now specifically has this rule:

```css
.umb-mediapicker .picked-image {
  ...
  display: none;
  ...
}
```

Maybe better to use a couple of classes that are specific to this plugin? (e.g.: `.emp-edit-image` and `.emp-remove-image` or similar?)
